"""Utilities for formatting grounded answers with citations."""

from pathlib import Path

from src.retrievers.retrieval_result import RetrievalResult


def format_answer(
    answer: str,
    documents: list[RetrievalResult],
) -> str:
    """Format a generated answer together with its citations.

    Args:
        answer: The answer generated by the language model.
        documents: Retrieved documents supporting the answer.

    Returns:
        A formatted string containing the answer and citations.

    Raises:
        ValueError: If the answer is empty or no documents are provided.
    """
    if not answer or not answer.strip():
        raise ValueError("Answer must not be empty.")

    if not documents:
        raise ValueError("Documents must not be empty.")

    citations: list[str] = []

    for index, result in enumerate(documents, start=1):
        metadata = result.document.metadata

        source = metadata.get("source", "Unknown")
        filename = Path(str(source)).name

        page = metadata.get("page", "Unknown")
        chunk_id = metadata.get("chunk_id", "Unknown")

        citations.append(
            f"[{index}] {filename} | "
            f"Page {page} | "
            f"Chunk {chunk_id}"
        )

    citation_block = "\n".join(citations)

    return (
        f"{answer}\n\n"
        "Sources:\n"
        f"{citation_block}"
    )